nginx:
  build: ./docker/nginx
  command: nginx -c /etc/nginx/nginx.conf -g "daemon off;"
  environment:
    - TERM=xterm-256color
  ports:
    - '80:80'
    - '8000:8000'
  links:
    - service:payments-service
  volumes:
    - ./docker/source-links/payments-example/public/:/srv/payments-example
    - ./docker/source-links/payments-ui/public/:/srv/payments-ui

service:
  image: mozillamarketplace/payments-service
  command: supervisord -n -c /srv/payments-service/docker/supervisor.conf
  environment:
    - PYTHONUNBUFFERED=1
    - PYTHONDONTWRITEBYTECODE=1
    - TERM=xterm-256color
  hostname: payments-service
  links:
    - solitude:solitude
  volumes:
    - ./docker/source-links/payments-service/:/srv/payments-service
  working_dir: /srv/payments-service

solitude:
  image: mozillamarketplace/solitude
  command: supervisord -n -c /srv/solitude/bin/docker/supervisor.conf
  environment:
    - PYTHONUNBUFFERED=1
    - PYTHONDONTWRITEBYTECODE=1
    - TERM=xterm-256color
  hostname: solitude
  links:
    - mysql:mysql
  volumes:
    - ./docker/source-links/solitude/:/srv/solitude
  working_dir: /srv/solitude

mysql:
  image: mozillamarketplace/mysql-service
  environment:
    - TERM=xterm-256color
  volumes_from:
    - mysqldata

mysqldata:
  image: mozillamarketplace/mysql-data
