# This is for deployments, where the volume source is not overridden. For a
# development set of containers, please see docker-compose.yml

# nginx container doesn't have the code in it so set up the volumes.
nginx:
  extends:
      file: configs/base.yml
      service: nginx
  links:
    - service:payments-service
  volumes_from:
    - example
    - logs
    - ui

service:
  extends:
      file: configs/base.yml
      service: service
  links:
    - solitude:solitude

solitude:
  extends:
      file: configs/base.yml
      service: solitude
  links:
    - mysql:mysql
  volumes_from:
    - logs

mysql:
  extends:
      file: configs/base.yml
      service: mysql
  volumes_from:
    - mysqldata

mysqldata:
  extends:
      file: configs/base.yml
      service: mysqldata

ui:
  extends:
      file: configs/base.yml
      service: ui

example:
  extends:
      file: configs/base.yml
      service: example

logs:
  extends:
      file: configs/base.yml
      service: logs
