# This is the default docker compose file that is useful for development
# since it overrides the volumes with local source. Consider using
# docker-compose-deploy.yml for deployments where you don't want the source.
nginx:
  extends:
      file: configs/base.yml
      service: nginx
  links:
    - service:payments-service
  volumes-from:
    - payments-example
    - payments-ui

service:
  extends:
      file: configs/base.yml
      service: service
  links:
    - solitude:solitude
  volumes:
    - ./docker/source-links/payments-service/:/srv/payments-service

solitude:
  extends:
      file: configs/base.yml
      service: solitude
  links:
    - mysql:mysql
  volumes:
    - ./docker/source-links/solitude/:/srv/solitude
  working_dir: /srv/solitude

mysql:
  extends:
      file: configs/base.yml
      service: mysql
  volumes_from:
    - mysqldata

mysqldata:
  extends:
      file: configs/base.yml
      service: mysqldata

ui:
  extends:
      file: configs/base.yml
      service: ui
  volumes:
    - ./docker/source-links/payments-ui/public/:/srv/payments-ui

example:
  extends:
      file: configs/base.yml
      service: example
  volumes:
    - ./docker/source-links/payments-example/public/:/srv/payments-example
