service:
  image: mozillamarketplace/payments-service
  command: supervisord -n -c /srv/payments-service/docker/supervisor.conf
  environment:
    - PYTHONUNBUFFERED=1
    - PYTHONDONTWRITEBYTECODE=1
    - TERM=xterm-256color
  hostname: payments-service
  links:
    - solitude:solitude
  volumes:
    - ./payments-service/:/srv/payments-service
  working_dir: /srv/payments-service

solitude:
  image: mozillamarketplace/solitude
  command: supervisord -n -c /srv/solitude/bin/docker/supervisor.conf
  environment:
    - PYTHONUNBUFFERED=1
    - PYTHONDONTWRITEBYTECODE=1
    - TERM=xterm-256color
    - ZIPPY_BASE_URL=http://zippy:2605/zippy
  hostname: solitude
  links:
    - mysql:mysql
  volumes:
    - ./solitude/:/srv/solitude
  working_dir: /srv/solitude

mysql:
  image: mozillamarketplace/mysql-service
  environment:
    - TERM=xterm-256color
  volumes_from:
    - mysqldata

mysqldata:
  image: mozillamarketplace/mysql-data
